pylint:
	@echo -e ${green} Running pylint on common files${nocol}
	pylint --disable=missing-docstring circumference.py
	pylint --disable=missing-docstring land.py
	pylint --disable=missing-docstring point.py

